// Copies the sample book's viewer page into public/, where the landing page embeds
// it. The page is generated by `pi.py html` into ../example/, and that file stays
// the only copy under version control, so the site always shows the viewer as it
// ships.
import { copyFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const source = resolve(here, "../../example/preview-node-index.html");
const target = resolve(here, "../public/demo/shokunin.html");

mkdirSync(dirname(target), { recursive: true });
copyFileSync(source, target);
console.log(`demo: ${source} -> ${target}`);
